import 'package:hive/hive.dart';
import 'package:lore_keeper/models/timeline_event.dart';
import 'package:lore_keeper/models/classification_node.dart';

/// Current persistence schema version for the Lore Keeper database.
///
/// This is independent of Hive TypeIds and entity revisions.
/// Increment this when the persistence structure changes (new boxes,
/// new required fields, renamed fields, structural migrations).
const int currentSchemaVersion = 2;

@HiveType(typeId: 50)
class DatabaseMetadata extends HiveObject {
  /// Persistence schema version. Checked on boot; triggers migrations when
  /// the stored value is less than [currentSchemaVersion].
  @HiveField(0)
  int schemaVersion;

  /// Stable database identity. Generated once on first boot and never changes.
  /// Used to verify database continuity across app updates.
  @HiveField(1)
  String databaseId;

  /// When this database was originally created.
  @HiveField(2)
  DateTime createdAt;

  /// When the last schema migration completed successfully.
  @HiveField(3)
  DateTime? lastMigrationAt;

  /// Version of the reference index stored in this database.
  /// Increment when the reference index format changes.
  /// This is independent of [schemaVersion].
  @HiveField(4)
  int referenceIndexVersion;

  /// ID of the AI model used to generate derived metadata, if any.
  /// Null when no model is installed or AI is disabled.
  @HiveField(5)
  String? aiModelId;

  /// Version string of the AI model used to generate derived metadata.
  /// Null when no model is installed.
  @HiveField(6)
  String? aiModelVersion;

  DatabaseMetadata({
    required this.schemaVersion,
    required this.databaseId,
    required this.createdAt,
    this.lastMigrationAt,
    this.referenceIndexVersion = 0,
    this.aiModelId,
    this.aiModelVersion,
  });

  /// Creates a fresh metadata record for a brand-new database.
  factory DatabaseMetadata.fresh() => DatabaseMetadata(
    schemaVersion: currentSchemaVersion,
    databaseId: _generateId(),
    createdAt: DateTime.now(),
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DatabaseMetadata &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          databaseId == other.databaseId;

  @override
  int get hashCode => schemaVersion.hashCode ^ databaseId.hashCode;

  static String _generateId() {
    final now = DateTime.now().millisecondsSinceEpoch;
    final rand = now.hashCode ^ (now >> 16);
    return 'db_${now.toRadixString(36)}_${rand.toRadixString(36)}';
  }
}

/// Hand-written Hive adapter for [DatabaseMetadata].
///
/// Normally generated by build_runner + hive_generator. Written manually
/// because the project's dev_dependencies have a pre-existing version
/// conflict that prevents build_runner from resolving.
class DatabaseMetadataAdapter extends TypeAdapter<DatabaseMetadata> {
  @override
  final int typeId = 50;

  @override
  DatabaseMetadata read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return DatabaseMetadata(
      schemaVersion: fields[0] as int,
      databaseId: fields[1] as String,
      createdAt: fields[2] as DateTime,
      lastMigrationAt: fields[3] as DateTime?,
      referenceIndexVersion: fields[4] as int? ?? 0,
      aiModelId: fields[5] as String?,
      aiModelVersion: fields[6] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, DatabaseMetadata obj) {
    writer
      ..writeByte(7)
      ..writeByte(0)
      ..write(obj.schemaVersion)
      ..writeByte(1)
      ..write(obj.databaseId)
      ..writeByte(2)
      ..write(obj.createdAt)
      ..writeByte(3)
      ..write(obj.lastMigrationAt)
      ..writeByte(4)
      ..write(obj.referenceIndexVersion)
      ..writeByte(5)
      ..write(obj.aiModelId)
      ..writeByte(6)
      ..write(obj.aiModelVersion);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DatabaseMetadataAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

/// Hand-written Hive adapter for [TimelineEvent].
///
/// Normally generated by build_runner + hive_generator. Written manually
/// because the project's dev_dependencies have a pre-existing version
/// conflict that prevents build_runner from resolving.
class TimelineEventAdapter extends TypeAdapter<TimelineEvent> {
  @override
  final int typeId = 29;

  @override
  TimelineEvent read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return TimelineEvent(
      id: fields[0] as String,
      projectId: fields[1] as int,
      name: fields[2] as String,
      tier: fields[3] as String,
      absoluteYear: fields[4] as int,
      absoluteDayOfYear: fields[5] as int,
      iconKey: fields[6] as String,
      colorValue: fields[7] as int,
      lore: fields[8] as String,
      createdAt: fields[9] as int,
      updatedAt: fields[10] as int,
      calendarSystemKey: fields[11] as int? ?? 0,
      durationDays: fields[12] as int? ?? 0,
      linkedCharacterIds: (fields[13] as List?)?.cast<String>() ?? [],
      linkedLocationIds: (fields[14] as List?)?.cast<String>() ?? [],
      endYear: fields[15] as int? ?? 0,
      endDayOfYear: fields[16] as int? ?? 0,
    );
  }

  @override
  void write(BinaryWriter writer, TimelineEvent obj) {
    writer
      ..writeByte(17)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.projectId)
      ..writeByte(2)
      ..write(obj.name)
      ..writeByte(3)
      ..write(obj.tier)
      ..writeByte(4)
      ..write(obj.absoluteYear)
      ..writeByte(5)
      ..write(obj.absoluteDayOfYear)
      ..writeByte(6)
      ..write(obj.iconKey)
      ..writeByte(7)
      ..write(obj.colorValue)
      ..writeByte(8)
      ..write(obj.lore)
      ..writeByte(9)
      ..write(obj.createdAt)
      ..writeByte(10)
      ..write(obj.updatedAt)
      ..writeByte(11)
      ..write(obj.calendarSystemKey)
      ..writeByte(12)
      ..write(obj.durationDays)
      ..writeByte(13)
      ..write(obj.linkedCharacterIds)
      ..writeByte(14)
      ..write(obj.linkedLocationIds)
      ..writeByte(15)
      ..write(obj.endYear)
      ..writeByte(16)
      ..write(obj.endDayOfYear);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineEventAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

/// Hand-written Hive adapter for [ClassificationNode].
///
/// Normally generated by build_runner + hive_generator. Written manually
/// because the project's dev_dependencies have a pre-existing version
/// conflict that prevents build_runner from resolving.
class ClassificationNodeAdapter extends TypeAdapter<ClassificationNode> {
  @override
  final int typeId = 36;

  @override
  ClassificationNode read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return ClassificationNode(
      id: fields[0] as String,
      projectId: fields[1] as int,
      parentId: fields[2] as String?,
      rank: fields[3] as String,
      name: fields[4] as String,
      normalizedName: fields[5] as String,
      content: fields[6] as String,
      iconKey: fields[7] as String,
      colorValue: fields[8] as int,
      childrenOrder: (fields[9] as List?)?.cast<String>() ?? [],
      createdAt: fields[10] as int,
      updatedAt: fields[11] as int,
      scientificName: fields[12] as String?,
      status: fields[13] as String? ?? 'Extant',
      origin: fields[14] as String?,
      averageLifespan: fields[15] as String? ?? '',
      averageHeight: fields[16] as String? ?? '',
      reproduction: fields[17] as String? ?? '',
      diet: fields[18] as String? ?? '',
      sentience: fields[19] as String? ?? '',
      population: fields[20] as String?,
      physiology: fields[21] as String? ?? '',
    );
  }

  @override
  void write(BinaryWriter writer, ClassificationNode obj) {
    writer
      ..writeByte(22)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.projectId)
      ..writeByte(2)
      ..write(obj.parentId)
      ..writeByte(3)
      ..write(obj.rank)
      ..writeByte(4)
      ..write(obj.name)
      ..writeByte(5)
      ..write(obj.normalizedName)
      ..writeByte(6)
      ..write(obj.content)
      ..writeByte(7)
      ..write(obj.iconKey)
      ..writeByte(8)
      ..write(obj.colorValue)
      ..writeByte(9)
      ..write(obj.childrenOrder)
      ..writeByte(10)
      ..write(obj.createdAt)
      ..writeByte(11)
      ..write(obj.updatedAt)
      ..writeByte(12)
      ..write(obj.scientificName)
      ..writeByte(13)
      ..write(obj.status)
      ..writeByte(14)
      ..write(obj.origin)
      ..writeByte(15)
      ..write(obj.averageLifespan)
      ..writeByte(16)
      ..write(obj.averageHeight)
      ..writeByte(17)
      ..write(obj.reproduction)
      ..writeByte(18)
      ..write(obj.diet)
      ..writeByte(19)
      ..write(obj.sentience)
      ..writeByte(20)
      ..write(obj.population)
      ..writeByte(21)
      ..write(obj.physiology);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClassificationNodeAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

/// Hand-written Hive adapter for [ClassificationArticle].
class ClassificationArticleAdapter extends TypeAdapter<ClassificationArticle> {
  @override
  final int typeId = 37;

  @override
  ClassificationArticle read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return ClassificationArticle(
      nodeId: fields[0] as String,
      projectId: fields[1] as int,
      content: fields[2] as String,
      updatedAt: fields[3] as int,
    );
  }

  @override
  void write(BinaryWriter writer, ClassificationArticle obj) {
    writer
      ..writeByte(4)
      ..writeByte(0)
      ..write(obj.nodeId)
      ..writeByte(1)
      ..write(obj.projectId)
      ..writeByte(2)
      ..write(obj.content)
      ..writeByte(3)
      ..write(obj.updatedAt);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClassificationArticleAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
