import 'package:hive/hive.dart';

part 'map_model.g.dart'; // This line is correct, the file will be generated by build_runner

@HiveType(typeId: 22) // Ensure this typeId is unique
class MapModel extends HiveObject {
  @HiveField(0)
  late dynamic id;

  @HiveField(1)
  late dynamic name;

  @HiveField(2)
  late dynamic projectId;

  @HiveField(3)
  dynamic style;

  @HiveField(4)
  dynamic resolution;

  @HiveField(5)
  dynamic aspectRatio;

  @HiveField(6)
  dynamic gridType;

  @HiveField(7)
  DateTime? created;

  @HiveField(8)
  DateTime? lastModified;

  MapModel({
    required this.id,
    required this.name,
    required this.projectId,
    this.style,
    this.resolution,
    this.aspectRatio,
    this.gridType,
    DateTime? created,
    DateTime? lastModified,
  }) : created = created ?? DateTime.now(),
       lastModified = lastModified ?? DateTime.now();

  factory MapModel.fromJson(Map<String, dynamic> json) {
    return MapModel(
      id: json['id'] as String,
      name: json['name'] as String,
      projectId: json['projectId'] as int,
      style: json['style'] as String?,
      resolution: json['resolution'] as String?,
      aspectRatio: json['aspectRatio'] as String?,
      gridType: json['gridType'] as String?,
      created: json['created'] != null
          ? DateTime.parse(json['created'] as String)
          : null,
      lastModified: json['lastModified'] != null
          ? DateTime.parse(json['lastModified'] as String)
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'projectId': projectId,
      'style': style,
      'resolution': resolution,
      'aspectRatio': aspectRatio,
      'gridType': gridType,
      'created': created?.toIso8601String(),
      'lastModified': lastModified?.toIso8601String(),
    };
  }
}
